# -*- coding: utf-8 -*-
"""Copia de CLASE _8_8 DE SEPTIEMBRE 2022.DANI CALA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_hbVJuhPWhgGzM23wuOtmsM9nVYpKLXF

<center>



#**COLEGIO SIGLO XXI-EL SOCORRO**
#**PRESENTADO A: ING PAOLA ANDREA QUINTERO**
#**PRESENTADO POR: DANIELA CALA PLATA**
#**GRADO DÉCIMO**
#**08 DE SEPTIEMBRE**

#**¿QUÈ ES PYTHON?**
#El lenguaje de programación Python es ampliamente utilizado por empresas de todo el mundo para construir aplicaciones web, analizar datos, automatizar operaciones y crear aplicaciones empresariales fiables y escalables.
#**FECHA DE NACIMIENTO:**
#1991
#**CREADOR**
#Guido Van Rossum
#**RECUPERADO DE**
#https://www.esic.edu/rethink/tecnologia/para-que-sirve-python
"""



print("esto es una suma")
numero_uno=7
numero_dos=6
resultado=numero_uno + numero_dos
print(resultado)

print("esto es una resta")
numero_uno=120
numero_dos=107
resultado=numero_uno - numero_dos
print(resultado)

print("esto es una multiplicación")
numero_uno=13
numero_dos=1
resultado=numero_uno * numero_dos
print(resultado)

print("esto es una división")
numero_uno=26
numero_dos=2
resultado=numero_uno / numero_dos
print(resultado)

"""#Ejercicios de tipos de datos simples

## Ejercicio 1

Escribir un programa que pregunte el nombre del usuario en la consola y un numero entero e impreima por pantalla  en lineas distintas el nombre del usuario tantas veces como el numero introducido
"""

nombre = input("¿cómo te llamas?")
n = input("introduce un número entero: ")
print((nombre + "\n") *int(n))

"""## EJERCICIO 2

Escribir un programa que pida al usuario su peso (en KG) y estatura (en M),
calcule el indice de masa corporal y lo almacene en una variable, e imprima por pantalla la frase 'tu indice de masa corporal es <imc>' donde  '<imc>' es el indice de masa corporal calculado redondeado con dos decimales 

"""

peso = input("¿cual es tu peso en KG?")
estatura = input("¿cual es tu estatura en M?")
imc = round(float(peso)/float(estatura)**2,2)
print("tu indice de masa corporal es " + str(imc))



"""# **LÍBRERIAS EN PHYTON**
# ¿Que es?:
#En este sentido, una librería es un conjunto de archivos que se utiliza para desarrollar software. Suele estar compuesta de código y datos, y su fin es ser utilizada por otros programas de forma totalmente autónoma. Simple y llanamente, es un archivo importable.
"""